version: "3.3"

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  reverseproxy:
    container_name: reverse-proxy-nginx
    ports:
      - '80:80'
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    environment:
      - PROXY=1
    restart: always
    image: owasp/modsecurity-crs:nginx-alpine

  wordpress:
    depends_on:
      - db
    ports:
      - '8080:80'
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: dbpassword
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:
  wordpress_data: